//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSharing.CommentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommentService.ICommentService")]
    public interface ICommentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/ChangeText", ReplyAction="http://tempuri.org/ICommentService/ChangeTextResponse")]
        void ChangeText(int id, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/ChangeText", ReplyAction="http://tempuri.org/ICommentService/ChangeTextResponse")]
        System.Threading.Tasks.Task ChangeTextAsync(int id, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/GetComment", ReplyAction="http://tempuri.org/ICommentService/GetCommentResponse")]
        ImageSharing.DAL.Entity.Comment GetComment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/GetComment", ReplyAction="http://tempuri.org/ICommentService/GetCommentResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Comment> GetCommentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/GetComments", ReplyAction="http://tempuri.org/ICommentService/GetCommentsResponse")]
        ImageSharing.DAL.Entity.Comment[] GetComments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/GetComments", ReplyAction="http://tempuri.org/ICommentService/GetCommentsResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Comment[]> GetCommentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/AddComment", ReplyAction="http://tempuri.org/ICommentService/AddCommentResponse")]
        void AddComment(ImageSharing.DAL.Entity.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/AddComment", ReplyAction="http://tempuri.org/ICommentService/AddCommentResponse")]
        System.Threading.Tasks.Task AddCommentAsync(ImageSharing.DAL.Entity.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/RemoveComment", ReplyAction="http://tempuri.org/ICommentService/RemoveCommentResponse")]
        void RemoveComment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommentService/RemoveComment", ReplyAction="http://tempuri.org/ICommentService/RemoveCommentResponse")]
        System.Threading.Tasks.Task RemoveCommentAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommentServiceChannel : ImageSharing.CommentService.ICommentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommentServiceClient : System.ServiceModel.ClientBase<ImageSharing.CommentService.ICommentService>, ImageSharing.CommentService.ICommentService {
        
        public CommentServiceClient() {
        }
        
        public CommentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeText(int id, string text) {
            base.Channel.ChangeText(id, text);
        }
        
        public System.Threading.Tasks.Task ChangeTextAsync(int id, string text) {
            return base.Channel.ChangeTextAsync(id, text);
        }
        
        public ImageSharing.DAL.Entity.Comment GetComment(int id) {
            return base.Channel.GetComment(id);
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Comment> GetCommentAsync(int id) {
            return base.Channel.GetCommentAsync(id);
        }
        
        public ImageSharing.DAL.Entity.Comment[] GetComments() {
            return base.Channel.GetComments();
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Comment[]> GetCommentsAsync() {
            return base.Channel.GetCommentsAsync();
        }
        
        public void AddComment(ImageSharing.DAL.Entity.Comment comment) {
            base.Channel.AddComment(comment);
        }
        
        public System.Threading.Tasks.Task AddCommentAsync(ImageSharing.DAL.Entity.Comment comment) {
            return base.Channel.AddCommentAsync(comment);
        }
        
        public void RemoveComment(int id) {
            base.Channel.RemoveComment(id);
        }
        
        public System.Threading.Tasks.Task RemoveCommentAsync(int id) {
            return base.Channel.RemoveCommentAsync(id);
        }
    }
}
