//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSharing.PostService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostService.IPostService")]
    public interface IPostService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/ChangeImagePath", ReplyAction="http://tempuri.org/IPostService/ChangeImagePathResponse")]
        void ChangeImagePath(int id, string photoPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/ChangeImagePath", ReplyAction="http://tempuri.org/IPostService/ChangeImagePathResponse")]
        System.Threading.Tasks.Task ChangeImagePathAsync(int id, string photoPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/ChangeDataTime", ReplyAction="http://tempuri.org/IPostService/ChangeDataTimeResponse")]
        void ChangeDataTime(int id, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/ChangeDataTime", ReplyAction="http://tempuri.org/IPostService/ChangeDataTimeResponse")]
        System.Threading.Tasks.Task ChangeDataTimeAsync(int id, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetPost", ReplyAction="http://tempuri.org/IPostService/GetPostResponse")]
        ImageSharing.DAL.Entity.Post GetPost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetPost", ReplyAction="http://tempuri.org/IPostService/GetPostResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Post> GetPostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetPosts", ReplyAction="http://tempuri.org/IPostService/GetPostsResponse")]
        ImageSharing.DAL.Entity.Post[] GetPosts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetPosts", ReplyAction="http://tempuri.org/IPostService/GetPostsResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Post[]> GetPostsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/AddPost", ReplyAction="http://tempuri.org/IPostService/AddPostResponse")]
        void AddPost(ImageSharing.DAL.Entity.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/AddPost", ReplyAction="http://tempuri.org/IPostService/AddPostResponse")]
        System.Threading.Tasks.Task AddPostAsync(ImageSharing.DAL.Entity.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/RemovePost", ReplyAction="http://tempuri.org/IPostService/RemovePostResponse")]
        void RemovePost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/RemovePost", ReplyAction="http://tempuri.org/IPostService/RemovePostResponse")]
        System.Threading.Tasks.Task RemovePostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/ChangeDescription", ReplyAction="http://tempuri.org/IPostService/ChangeDescriptionResponse")]
        void ChangeDescription(int id, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/ChangeDescription", ReplyAction="http://tempuri.org/IPostService/ChangeDescriptionResponse")]
        System.Threading.Tasks.Task ChangeDescriptionAsync(int id, string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPostServiceChannel : ImageSharing.PostService.IPostService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostServiceClient : System.ServiceModel.ClientBase<ImageSharing.PostService.IPostService>, ImageSharing.PostService.IPostService {
        
        public PostServiceClient() {
        }
        
        public PostServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeImagePath(int id, string photoPath) {
            base.Channel.ChangeImagePath(id, photoPath);
        }
        
        public System.Threading.Tasks.Task ChangeImagePathAsync(int id, string photoPath) {
            return base.Channel.ChangeImagePathAsync(id, photoPath);
        }
        
        public void ChangeDataTime(int id, System.DateTime dateTime) {
            base.Channel.ChangeDataTime(id, dateTime);
        }
        
        public System.Threading.Tasks.Task ChangeDataTimeAsync(int id, System.DateTime dateTime) {
            return base.Channel.ChangeDataTimeAsync(id, dateTime);
        }
        
        public ImageSharing.DAL.Entity.Post GetPost(int id) {
            return base.Channel.GetPost(id);
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Post> GetPostAsync(int id) {
            return base.Channel.GetPostAsync(id);
        }
        
        public ImageSharing.DAL.Entity.Post[] GetPosts() {
            return base.Channel.GetPosts();
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Post[]> GetPostsAsync() {
            return base.Channel.GetPostsAsync();
        }
        
        public void AddPost(ImageSharing.DAL.Entity.Post post) {
            base.Channel.AddPost(post);
        }
        
        public System.Threading.Tasks.Task AddPostAsync(ImageSharing.DAL.Entity.Post post) {
            return base.Channel.AddPostAsync(post);
        }
        
        public void RemovePost(int id) {
            base.Channel.RemovePost(id);
        }
        
        public System.Threading.Tasks.Task RemovePostAsync(int id) {
            return base.Channel.RemovePostAsync(id);
        }
        
        public void ChangeDescription(int id, string text) {
            base.Channel.ChangeDescription(id, text);
        }
        
        public System.Threading.Tasks.Task ChangeDescriptionAsync(int id, string text) {
            return base.Channel.ChangeDescriptionAsync(id, text);
        }
    }
}
