//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSharing.TapeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TapeService.ITapeService")]
    public interface ITapeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/GetTape", ReplyAction="http://tempuri.org/ITapeService/GetTapeResponse")]
        ImageSharing.DAL.Entity.Tape GetTape(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/GetTape", ReplyAction="http://tempuri.org/ITapeService/GetTapeResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Tape> GetTapeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/GetTapes", ReplyAction="http://tempuri.org/ITapeService/GetTapesResponse")]
        ImageSharing.DAL.Entity.Tape[] GetTapes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/GetTapes", ReplyAction="http://tempuri.org/ITapeService/GetTapesResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Tape[]> GetTapesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/AddTape", ReplyAction="http://tempuri.org/ITapeService/AddTapeResponse")]
        void AddTape(ImageSharing.DAL.Entity.Tape tape);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/AddTape", ReplyAction="http://tempuri.org/ITapeService/AddTapeResponse")]
        System.Threading.Tasks.Task AddTapeAsync(ImageSharing.DAL.Entity.Tape tape);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/RemoveTape", ReplyAction="http://tempuri.org/ITapeService/RemoveTapeResponse")]
        void RemoveTape(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITapeService/RemoveTape", ReplyAction="http://tempuri.org/ITapeService/RemoveTapeResponse")]
        System.Threading.Tasks.Task RemoveTapeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITapeServiceChannel : ImageSharing.TapeService.ITapeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TapeServiceClient : System.ServiceModel.ClientBase<ImageSharing.TapeService.ITapeService>, ImageSharing.TapeService.ITapeService {
        
        public TapeServiceClient() {
        }
        
        public TapeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TapeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TapeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TapeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ImageSharing.DAL.Entity.Tape GetTape(int id) {
            return base.Channel.GetTape(id);
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Tape> GetTapeAsync(int id) {
            return base.Channel.GetTapeAsync(id);
        }
        
        public ImageSharing.DAL.Entity.Tape[] GetTapes() {
            return base.Channel.GetTapes();
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.Tape[]> GetTapesAsync() {
            return base.Channel.GetTapesAsync();
        }
        
        public void AddTape(ImageSharing.DAL.Entity.Tape tape) {
            base.Channel.AddTape(tape);
        }
        
        public System.Threading.Tasks.Task AddTapeAsync(ImageSharing.DAL.Entity.Tape tape) {
            return base.Channel.AddTapeAsync(tape);
        }
        
        public void RemoveTape(int id) {
            base.Channel.RemoveTape(id);
        }
        
        public System.Threading.Tasks.Task RemoveTapeAsync(int id) {
            return base.Channel.RemoveTapeAsync(id);
        }
    }
}
