//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSharing.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        void AddUser(ImageSharing.DAL.Entity.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(ImageSharing.DAL.Entity.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        ImageSharing.DAL.Entity.UserAccount GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.UserAccount> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        ImageSharing.DAL.Entity.UserAccount[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        System.Threading.Tasks.Task<ImageSharing.DAL.Entity.UserAccount[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeName", ReplyAction="http://tempuri.org/IUserService/ChangeNameResponse")]
        void ChangeName(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeName", ReplyAction="http://tempuri.org/IUserService/ChangeNameResponse")]
        System.Threading.Tasks.Task ChangeNameAsync(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeSurname", ReplyAction="http://tempuri.org/IUserService/ChangeSurnameResponse")]
        void ChangeSurname(int id, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeSurname", ReplyAction="http://tempuri.org/IUserService/ChangeSurnameResponse")]
        System.Threading.Tasks.Task ChangeSurnameAsync(int id, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeEmail", ReplyAction="http://tempuri.org/IUserService/ChangeEmailResponse")]
        void ChangeEmail(int id, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeEmail", ReplyAction="http://tempuri.org/IUserService/ChangeEmailResponse")]
        System.Threading.Tasks.Task ChangeEmailAsync(int id, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        void ChangePassword(int id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        System.Threading.Tasks.Task ChangePasswordAsync(int id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeAvatarPath", ReplyAction="http://tempuri.org/IUserService/ChangeAvatarPathResponse")]
        void ChangeAvatarPath(int id, string avatarPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeAvatarPath", ReplyAction="http://tempuri.org/IUserService/ChangeAvatarPathResponse")]
        System.Threading.Tasks.Task ChangeAvatarPathAsync(int id, string avatarPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveUser", ReplyAction="http://tempuri.org/IUserService/RemoveUserResponse")]
        void RemoveUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveUser", ReplyAction="http://tempuri.org/IUserService/RemoveUserResponse")]
        System.Threading.Tasks.Task RemoveUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ActivateAccount", ReplyAction="http://tempuri.org/IUserService/ActivateAccountResponse")]
        void ActivateAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ActivateAccount", ReplyAction="http://tempuri.org/IUserService/ActivateAccountResponse")]
        System.Threading.Tasks.Task ActivateAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeRole", ReplyAction="http://tempuri.org/IUserService/ChangeRoleResponse")]
        void ChangeRole(int id, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeRole", ReplyAction="http://tempuri.org/IUserService/ChangeRoleResponse")]
        System.Threading.Tasks.Task ChangeRoleAsync(int id, string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : ImageSharing.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<ImageSharing.UserService.IUserService>, ImageSharing.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(ImageSharing.DAL.Entity.UserAccount user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(ImageSharing.DAL.Entity.UserAccount user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public ImageSharing.DAL.Entity.UserAccount GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.UserAccount> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public ImageSharing.DAL.Entity.UserAccount[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<ImageSharing.DAL.Entity.UserAccount[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public void ChangeName(int id, string name) {
            base.Channel.ChangeName(id, name);
        }
        
        public System.Threading.Tasks.Task ChangeNameAsync(int id, string name) {
            return base.Channel.ChangeNameAsync(id, name);
        }
        
        public void ChangeSurname(int id, string surname) {
            base.Channel.ChangeSurname(id, surname);
        }
        
        public System.Threading.Tasks.Task ChangeSurnameAsync(int id, string surname) {
            return base.Channel.ChangeSurnameAsync(id, surname);
        }
        
        public void ChangeEmail(int id, string email) {
            base.Channel.ChangeEmail(id, email);
        }
        
        public System.Threading.Tasks.Task ChangeEmailAsync(int id, string email) {
            return base.Channel.ChangeEmailAsync(id, email);
        }
        
        public void ChangePassword(int id, string password) {
            base.Channel.ChangePassword(id, password);
        }
        
        public System.Threading.Tasks.Task ChangePasswordAsync(int id, string password) {
            return base.Channel.ChangePasswordAsync(id, password);
        }
        
        public void ChangeAvatarPath(int id, string avatarPath) {
            base.Channel.ChangeAvatarPath(id, avatarPath);
        }
        
        public System.Threading.Tasks.Task ChangeAvatarPathAsync(int id, string avatarPath) {
            return base.Channel.ChangeAvatarPathAsync(id, avatarPath);
        }
        
        public void RemoveUser(int id) {
            base.Channel.RemoveUser(id);
        }
        
        public System.Threading.Tasks.Task RemoveUserAsync(int id) {
            return base.Channel.RemoveUserAsync(id);
        }
        
        public void ActivateAccount(int id) {
            base.Channel.ActivateAccount(id);
        }
        
        public System.Threading.Tasks.Task ActivateAccountAsync(int id) {
            return base.Channel.ActivateAccountAsync(id);
        }
        
        public void ChangeRole(int id, string role) {
            base.Channel.ChangeRole(id, role);
        }
        
        public System.Threading.Tasks.Task ChangeRoleAsync(int id, string role) {
            return base.Channel.ChangeRoleAsync(id, role);
        }
    }
}
